name: AWS EC2 login workflow

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
   login_ec2 :
    name: 'login ec2'
    runs-on: ubuntu-latest
   
    
    steps:
      - uses: actions/checkout@v2 
      - name: Create ssh
            
        run: |
          mkdir -p ~/.ssh/
          echo "$$PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$HOSTNAME" > ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          
      - name: login to ec2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key    
        shell: bash
        run: |
          ssh  -o StrictHostKeyChecking=no -i $SSH_KEY_PATH ubuntu@ec2-35-174-172-10.compute-1.amazonaws.com
